import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Home from './views/Home'
import Login from './views/Login'



export default function Index() {
  const [usuario, setUsuario] = useState(null)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        {usuario ? <Home /> : <Login />}
      </div>
    </>
  )
}
