import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Home from './views/Home'
import Login from './views/Login'
import { getAuth, onAuthStateChanged } from 'firebase/auth'

import firebaseApp from './firebase/credentials'

const auth = getAuth(firebaseApp)


function Index() {
  const [usuario, setUsuario] = useState(null)


  onAuthStateChanged(auth, (usuarioFirebase) => {
    if (usuarioFirebase) {
      setUsuario(usuarioFirebase);
    } else {
      setUsuario(null);
    }
  })


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {usuario ? <Home usuario={usuario} /> : <Login />}
      </div>
    </>
  )
}

export default Index
